{{- if not .Values.global.testCluster }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "eneo.fullname" . }}-backup-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ACCESS_KEY: AgAgQYSkdh6N47O1q0XsCKc0JaayjunUsYpKVWcHcEn3yaVP1Akff/73pA4X0rU97llMKkihLD4PkMoZsx/RahOgUn8sSQ+Bks+qP2xgS5o2iGWSgDJjNvdJwehDImSq9wtMB2K0pIcUcTkYXyQJIWkUsxOFw1ygvnGkKHbrxW9aj1S0cmj4yoc1knnOC6mx98I6p7dNSowSUJ1vIFX1RnLiO2W0Gk0+Db8FSXzQHAVWj8kLKUm5+m+MdQ73noTNF9lXtEmoyexMOUPpvmy3m+/ZdIAXpqXwuzKLoMISXOh4yDeqya025n1syKmpsaMk74VD3dVNpXiAD5DE7rd9ooXb/Yzywz5PvXxTHlaAnCcf/LtvqXz+/3i8q8MLHgXPnfG+qC7ZqwTOQ7ep3ZianccP3SnV1JvxGrGELYWEj/IPMN9qNe+2vBnSm1Uxnac6sFVqiTP8zQZWfM76Y2z9XuNnw2tN0VovIgyax6f5/jcSOBGOijcQn59oVHq7up1tTZD+ajOxBchvyD9Eji5bJjTIWN2cDN57hrIt3mQ8pLKSetvsfrNDubIlPtoJgJYsqPHatIitChW71NgtjFKDnoRPrbVVHhDDSVy4hNzgEiBCyfXDQweFCV2IzMDWXfrEg0XPO2b+PPnnPMcVx3++FRmY12GQ2d3Im6VWTWm/U48cTrzfgl+SV/MHYLzvfW/wlIsp/0WmKEibiZXtnurzRvVP04S+Bw==
    SECRET_KEY: AgDQY+tmZ0Hbih9UeZ/AEW8JupQDyugynkcevZpEyjvdyWudU2zmb8XcMvD2DDjuk87GvIOb2Al3BVm19tr9p5FF7mVd+SUw0ikhqg0zLlVeVoyl7o0D25YHN892xJpS1ngxVBYX0PSUjwsI5F7EZaMmynLQBcHmvSHVgzaXn7s6tC/SEWQAcwdeO8Rf44BTlXc5POh+HsQazT9EUOHnXRqDT4gVG2a69lUB4E6tonZDNsbiDe7nDmDCUgA1ci4jbdLxsuOvum61KI8yrLzL63YDwsZFvMqZS4TREnQ1V8AvBKRldSQciQVsE89AoqG7VrBrWBgG7InZqbrVI4V/dEvSk2hT2u7T6uyLwCOSypWDhGW8RPdJRpKG6/KpA6oQg1JNnP8Wmj5qU1DFpCFrX1Gy3OWycYk0vsgo+qbhab3zbS58kbDXnx4OrSeIwGWeSyrEX2NvqfeP5ah5sojyGRcSp/HixW4XzyijDqCMqZcbfjQ3sOpBd51klU14bz8QMSZDgbj9UqU/xiyNSFw++hNjgJn5OpvsC0PcWNqihEI+Fr63KKTEmzkuOEQgVeBTijYLFrIikn/N+00ZXVP7MvBqdPuM+9f/TNTGYzS95VAw9kjQ4hszby+Fc9GR4gt6hblywGLHOIRVIgYTp36FmjusdS93h1pgR3x3j/HUyBsNCydwuBIhePAtQChXifUhKl4j+1WqNGruBN9su3IZnM7uTeE/thgc2vBYAFjqJMxpUtb7ppFandcQ
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ include "eneo.fullname" . }}-backup-secret
      namespace: {{ .Release.Namespace }}
{{- end }}
