---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: {{ include "eneo.fullname" . }}-backup-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ACCESS_KEY: AgAD4sPG/HzzZCISJ6d89XYqxYaB9brYfLxuoqLq0sBJoN9OVT5Skxw9hKQeODhL46HAGL98myX7tUO9/bzRiPKikz8Mzn8mTMOIrL6iCw5AyC2C7t3xbLkiVP7uH4eQldy2SJ15feuNiaED/xwgW78jke863vYCkAbITpqKzfD3DE99F/T/DozCdk72MGym2C+Zu2xZcx+UTIJgjuNcnhc4ZOZzd/xng6foE8VFss9DXi5U9UQtsr+SZtBNNqP0+YQH756+WM+bZcNyd4RPvoaNIghG51XM70PaQknrhZR7cXjJ/zFNCfR/oOqS0++iOMRKIqQWjHXvmkAkFTYYVQyohSRLC4SxmJC5VXG8jsvQvBWfyVpqdHXriPdmznw9asiAwG2BHIQimglDfBAmiI7rztnjHfUY4Rq9P02jKedxst1cFET5gSR5aC3AqbGcVNY1OW3mpRNO+9BHTMv+hbzzcNeIqv5cG2E9zAw6c+R344UlGi08dW2ecsA5X/dB68onarRyJAsEyDEb0/+ROyFnsYEloZxaNBBmkiL1UFQwsQS5YKF0cV8jB9OoZWy4a23S7y0abTZSiJj7XkSblxTGRKiDxO93Ty76Rzn5Aef4MNarYKiJLMCqz+WnpDWrjTYN5LbgPmd9WB8RAxyGqgMec7mMDnKe+NQSZ4itFIlUb+beKPXDxikDvOgw3BebwDItYRpFSxt/RmMrOwLc1kSz+3Rjjw==
    SECRET_KEY: AgANybMRMq6aXzgvhR+3y7Uqi/6y/J27Axg5sMXTxRQBYhiYGOXqBJof4n/yX+eqiz+5++lws0XzJeiW5rjHo57A6Xe6BAZGdRsxiwyNna+PkyagelEvV0nD2mTFhbQSPw+StjjNwQrxYLqb82ePrcQJkVAzeMkiAz/I2Jwii3aLg47Eqcg7Np8v4Cb5xgZrxAmdyc7F/khdRzcrPWiCEEMFiMXQZl0YuhC+XK7lqcZ7VcsjhDt+syWLpOUt2zzmEQPGsLi7dsJaFe3a+h7c4M0uAeyOWqzoeG//qne9G7LhukA2eLK4rzKd/vDr8HlLvjLylx5Sn5pcWVo6aq+vhz54RkiSwCn0uQu7E7ZBSkYUbFVMirjduMuD2iwPjEe+K2bYpIC3NWor7/0gtroDskBWP/iO4Ogrk1x+sM0pEs0QT8Ee1vETeDj6cs95exOtrBQwhz7IRIer0NhHQSktM5zq64o8mP+FJ7LXYTkIgYbZugZ/EyM9YDQ9EgbnEDDfIqGVgoxxnBhzj/DAjzKO7Zhs7cIjoYsETDcRKs+mcOmL6SZXjKU3pOw6bTmUrYMgKll1oW4+EGbxF0RgmWq/LggFOC9widVi9sZtl2iBWsqlJIXwNORrOTeAmFcMQWzs+lrcgwQ43K61Xkc6fUr4kRQMvCgRvhrANHveT4hJhL0lD8l+fNi9iSwkf+dmDDerLjx48EGnEaF151zJ0x6TLC08HxWbTBVwuR6/QRw2GunhWbb7I0mpBGNwSFAB+B/2soC2YCs=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: {{ include "eneo.fullname" . }}-backup-secret
      namespace: {{ .Release.Namespace }}
