apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eneo.fullname" . }}-files
  labels:
    {{- include "eneo.labels" . | nindent 4 }}
data:
  ai_models.yml: |
{{ .Files.Get "files/ai_models.yml" | indent 4 }}
  gdm.py: |
{{ .Files.Get "files/gdm.py" | indent 4 }}
  oidc.json: |
{{ .Values.oidc | toJson | indent 4 }}
