apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ include "eneo.fullname" . }}-postgres-backup
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "0 0 0 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: {{ include "eneo.fullname" . }}-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io