apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "eneo.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": {{ include "eneo.fullname" . }}-postgres
  podMetricsEndpoints:
  - port: metrics