{{- if and .Values.postgres.enabled .Values.postgres.operatorManaged -}}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "eneo.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eneo.labels" . | nindent 4 }}
spec:
  imageName: {{ .Values.postgres.imageName }}
  instances: {{ .Values.postgres.instances }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.owner }}
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
  storage:
    size: {{ .Values.postgres.storage.size }}
{{- end }}
  backup:
    retentionPolicy: "30d"
    barmanObjectStore:
      destinationPath: s3://k8s-ai-eneo-services/
      endpointURL: https://s3bkp.k8s.gdmcloud.se
      s3Credentials:
        accessKeyId:
          name: {{ include "eneo.fullname" . }}-backup-secret
          key: ACCESS_KEY
        secretAccessKey:
          name: {{ include "eneo.fullname" . }}-backup-secret
          key: SECRET_KEY