{{- if .Values.redis.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eneo.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eneo.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "eneo.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "eneo.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.redis.service.targetPort }}
          name: redis
        {{- if .Values.redis.persistence.enabled }}
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        {{- end }}
      {{- if .Values.redis.persistence.enabled }}
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: {{ include "eneo.fullname" . }}-redis
      {{- end }}
{{- end }}
