apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n.fullname" . }}-files
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
data:
  setup.py: |
{{ .Files.Get "files/setup.py" | indent 4 }}
