{{- if and .Values.postgres.enabled .Values.postgres.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "n8n.fullname" . }}-pg
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": {{ include "n8n.fullname" . }}-postgres
  podMetricsEndpoints:
  - port: metrics
{{- end }}
