{{- $profile := include "n8n.profile" . | fromYaml -}}
{{- if eq (.Values.config.executionsMode | default $profile.config.executionsMode) "queue" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
{{- end }}
