{{- include "n8n.validateValues" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: {{ include "n8n.generateEncryptionKey" (dict "value" .Values.secrets.encryptionKey "context" .) | quote }}
  N8N_RUNNERS_AUTH_TOKEN: {{ include "n8n.generateRunnerToken" (dict "value" .Values.secrets.runnerToken "context" .) | quote }}
