apiVersion: v2
name: eneo
description: A Helm chart for eneo application
type: application
version: 1.0.58
appVersion: "1.6.0"
keywords:
  - eneo
  - ai
  - backend
  - frontend
maintainers:
  - name: GDM
