apiVersion: v2
name: n8n
description: A Helm chart for n8n workflow automation
type: application
version: 1.0.8
appVersion: "2.8.3"
keywords:
  - n8n
  - automation
  - workflow
maintainers:
  - name: GDM
